### ISSUE TITLE
Implement the actual shooting part

### ISSUE THREAD

**Issue by ClobberXD** [ClobberXD/sniper#1]
There are two parts to this:
- Retrieval of object in line-of-sight.
  - If I am correct, this should be doable using `Raycast` and `ObjectRef:get_look_dir`...
- Render bullet using particle API.
  - Damage dealt should be dependent on the speed of bullet (particle)

**Comment by skittlemittle** [comment]
>Render bullet

I don't think this is essential at all coz the one doing the sniping doesnt care if they see the bullet and seeing the bullet won't be useful for the victim since bullets from a sniy rilfe move fast and they won't see the bullet anyway

**Comment by ClobberXD** [comment]
@afshaan4: Particles to represent bullets is essential since bullet velocity seems to be determined only by the particles themselves. See the [`particle` definition](https://github.com/minetest/minetest/blob/88efebdf864baeb422cbe4d992a44ff7c99373fb/doc/lua_api.txt#L6367)

**Comment by ClobberXD** [comment]
Implementing the raycasting part for now, the bullet physics can come later...
